apiVersion: apps/v1
kind: Deployment
metadata:
  name: uts-devops-deployment

spec:
  replicas: 2

  selector:
    matchLabels:
      app: uts-devops

  template:
    metadata:
      labels:
        app: uts-devops

    spec:
      containers:
        - name: uts-devops
          image: uts-devops
          ports:
            - containerPort: 3000